"""Tests for the DeepEval evaluation node — LLM calls are mocked."""
import pytest
from unittest.mock import MagicMock, patch
from qa_framework_generator.state import GeneratedFile, ValidationResult


def _make_page_file(class_name: str = "HomePage", content: str = None) -> GeneratedFile:
    content = content or f"""// Generated by qa-framework-generator
package com.example.pages;

import com.example.base.BasePage;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

public class {class_name} extends BasePage {{
    private static final By SEARCH_INPUT = By.cssSelector("input[type='search']");

    public {class_name}(WebDriver driver) {{ super(driver); }}

    public void clickSearchInput() {{ click(SEARCH_INPUT); }}
}}
"""
    return GeneratedFile(
        path=f"src/test/java/com/example/pages/{class_name}.java",
        content=content,
        kind="java",
    )


def _make_test_file(class_name: str = "SmokeTest", content: str = None) -> GeneratedFile:
    content = content or f"""// Generated by qa-framework-generator
package com.example.tests;

import com.example.base.BaseTest;
import org.testng.Assert;
import org.testng.annotations.Test;

public class {class_name} extends BaseTest {{
    @Test(groups = {{"smoke"}}, retryAnalyzer = com.example.retry.RetryAnalyzer.class)
    public void {class_name[0].lower() + class_name[1:]}Test() {{
        Assert.assertTrue(driver.getTitle().length() > 0, "Title should not be empty");
    }}
}}
"""
    return GeneratedFile(
        path=f"src/test/java/com/example/tests/{class_name}.java",
        content=content,
        kind="java",
    )


_PAGE_SPEC = {"name": "HomePage", "path": "/", "elements": [{"name": "searchInput", "by": "css", "value": "input[type='search']"}]}
_FLOW_SPEC = {"name": "SmokeTest", "groups": ["smoke"], "steps": [{"open": "HomePage"}]}


# --- evaluate_page_object ---

def test_evaluate_page_object_passes_high_score():
    from qa_framework_generator.evaluator import evaluate_page_object
    mock_metric = MagicMock()
    mock_metric.score = 0.9
    mock_metric.reason = "All elements present and correct"

    with patch("qa_framework_generator.evaluator.GEval", return_value=mock_metric):
        result = evaluate_page_object(_make_page_file(), _PAGE_SPEC, threshold=0.7)

    assert result.passed is True
    assert "0.90" in result.output


def test_evaluate_page_object_fails_low_score():
    from qa_framework_generator.evaluator import evaluate_page_object
    mock_metric = MagicMock()
    mock_metric.score = 0.4
    mock_metric.reason = "Missing locators"

    with patch("qa_framework_generator.evaluator.GEval", return_value=mock_metric):
        result = evaluate_page_object(_make_page_file(), _PAGE_SPEC, threshold=0.7)

    assert result.passed is False
    assert "eval_page_object" in result.name


def test_evaluate_test_class_passes_high_score():
    from qa_framework_generator.evaluator import evaluate_test_class
    mock_metric = MagicMock()
    mock_metric.score = 0.85
    mock_metric.reason = "Groups and assertions present"

    with patch("qa_framework_generator.evaluator.GEval", return_value=mock_metric):
        result = evaluate_test_class(_make_test_file(), _FLOW_SPEC, threshold=0.7)

    assert result.passed is True


def test_evaluate_test_class_fails_low_score():
    from qa_framework_generator.evaluator import evaluate_test_class
    mock_metric = MagicMock()
    mock_metric.score = 0.3
    mock_metric.reason = "No assertions found"

    with patch("qa_framework_generator.evaluator.GEval", return_value=mock_metric):
        result = evaluate_test_class(_make_test_file(), _FLOW_SPEC, threshold=0.7)

    assert result.passed is False
    assert "eval_test_class" in result.name
    assert "SmokeTest" in result.name


# --- evaluate_generated_files ---

def test_evaluate_generated_files_returns_results_for_all():
    from qa_framework_generator.evaluator import evaluate_generated_files
    mock_metric = MagicMock()
    mock_metric.score = 0.9
    mock_metric.reason = "Good"

    files = [_make_page_file("HomePage"), _make_test_file("SmokeTest")]
    config_data = {
        "project_name": "test",
        "package_name": "com.example",
        "pages": [_PAGE_SPEC],
        "flows": [_FLOW_SPEC],
        "environments": {},
        "browsers": ["chrome"],
        "headless_default": True,
        "parallel": {"enabled": False, "thread_count": 1},
        "output_dir": "out",
    }

    with patch("qa_framework_generator.evaluator.GEval", return_value=mock_metric):
        results = evaluate_generated_files(files, config_data, threshold=0.7)

    assert len(results) == 2
    assert all(isinstance(r, ValidationResult) for r in results)


def test_evaluate_skips_non_page_non_test_files():
    from qa_framework_generator.evaluator import evaluate_generated_files
    mock_metric = MagicMock()
    mock_metric.score = 0.9
    mock_metric.reason = "Good"

    files = [
        GeneratedFile(path="pom.xml", content="<project/>", kind="xml"),
        GeneratedFile(path="README.md", content="# Hi", kind="markdown"),
        _make_page_file("HomePage"),
    ]
    config_data = {
        "project_name": "test",
        "package_name": "com.example",
        "pages": [_PAGE_SPEC],
        "flows": [],
        "environments": {},
        "browsers": ["chrome"],
        "headless_default": True,
        "parallel": {"enabled": False, "thread_count": 1},
        "output_dir": "out",
    }

    with patch("qa_framework_generator.evaluator.GEval", return_value=mock_metric):
        results = evaluate_generated_files(files, config_data, threshold=0.7)

    assert len(results) == 1
    assert results[0].name.startswith("eval_page_object")


# --- deepeval unavailable ---

def test_evaluate_returns_warning_when_deepeval_unavailable(monkeypatch):
    import qa_framework_generator.evaluator as ev_mod
    monkeypatch.setattr(ev_mod, "_DEEPEVAL_AVAILABLE", False)
    from qa_framework_generator.evaluator import evaluate_generated_files
    results = evaluate_generated_files([], {})
    assert len(results) == 1
    assert results[0].name == "eval_deepeval_unavailable"
    assert results[0].passed is True
    assert "deepeval" in results[0].output.lower()


def test_evaluate_warning_does_not_block_routing(monkeypatch):
    import qa_framework_generator.evaluator as ev_mod
    monkeypatch.setattr(ev_mod, "_DEEPEVAL_AVAILABLE", False)
    from qa_framework_generator.graph import route_after_evaluation
    from qa_framework_generator.state import GeneratorState
    from qa_framework_generator.evaluator import evaluate_generated_files

    results = evaluate_generated_files([], {})
    state = GeneratorState(validation_results=results)
    assert route_after_evaluation(state) == "write_files"


# --- graph routing ---

def test_route_after_evaluation_passes():
    from qa_framework_generator.graph import route_after_evaluation
    from qa_framework_generator.state import GeneratorState

    state = GeneratorState(
        validation_results=[
            ValidationResult(name="eval_page_object_HomePage", passed=True, output="Score: 0.90"),
            ValidationResult(name="eval_test_class_SmokeTest", passed=True, output="Score: 0.85"),
        ]
    )
    assert route_after_evaluation(state) == "write_files"


def test_route_after_evaluation_fails():
    from qa_framework_generator.graph import route_after_evaluation
    from qa_framework_generator.state import GeneratorState

    state = GeneratorState(
        validation_results=[
            ValidationResult(name="eval_page_object_HomePage", passed=False, output="Score: 0.40"),
        ]
    )
    assert route_after_evaluation(state) == "repair"


def test_route_after_evaluation_no_eval_results_passes():
    from qa_framework_generator.graph import route_after_evaluation
    from qa_framework_generator.state import GeneratorState

    state = GeneratorState(validation_results=[])
    assert route_after_evaluation(state) == "write_files"
