from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from qa_framework_generator.state import GeneratedFile

GENERATED_MARKER = "Generated by qa-framework-generator"


def _prepend_header(content: str, kind: str) -> str:
    if kind == "java":
        return f"// {GENERATED_MARKER}\n{content}"
    if kind in ("xml",):
        # Insert comment after the XML declaration if present
        lines = content.splitlines(keepends=True)
        if lines and lines[0].strip().startswith("<?xml"):
            return lines[0] + f"<!-- {GENERATED_MARKER} -->\n" + "".join(lines[1:])
        return f"<!-- {GENERATED_MARKER} -->\n{content}"
    if kind in ("properties", "yaml", "text"):
        return f"# {GENERATED_MARKER}\n{content}"
    return content


def _is_generated(existing: str) -> bool:
    return GENERATED_MARKER in existing


@dataclass
class WriteResult:
    written: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    deleted: list[str] = field(default_factory=list)


def _prune_empty_dirs(base: Path) -> None:
    for dirpath in sorted(base.rglob("*"), reverse=True):
        if dirpath.is_dir() and dirpath != base:
            try:
                dirpath.rmdir()
            except OSError:
                pass


def write_files(
    files: list[GeneratedFile],
    output_dir: str,
    force: bool = False,
) -> WriteResult:
    base = Path(output_dir)
    result = WriteResult()

    current_paths = {(base / gf.path).resolve() for gf in files}

    for gf in files:
        dest = base / gf.path
        dest.parent.mkdir(parents=True, exist_ok=True)

        if dest.exists() and not force:
            if not _is_generated(dest.read_text(encoding="utf-8")):
                result.skipped.append(str(dest))
                continue

        final_content = _prepend_header(gf.content, gf.kind)
        dest.write_text(final_content, encoding="utf-8")
        result.written.append(str(dest))

    if base.exists():
        for existing in base.rglob("*"):
            if existing.is_file() and existing.resolve() not in current_paths:
                try:
                    text = existing.read_text(encoding="utf-8", errors="ignore")
                except OSError:
                    continue
                if _is_generated(text):
                    rel = str(existing.relative_to(base))
                    existing.unlink()
                    result.deleted.append(rel)
        _prune_empty_dirs(base)

    return result
